export interface TopCity {
  slug: string
  nom: string
  departement: string
  region: string
}

export const TOP_FRENCH_CITIES_LIST: TopCity[] = [
  { slug: 'paris', nom: 'Paris', departement: '75 - Paris', region: 'Île-de-France' },
  { slug: 'marseille', nom: 'Marseille', departement: '13 - Bouches-du-Rhône', region: 'Provence-Alpes-Côte d\'Azur' },
  { slug: 'lyon', nom: 'Lyon', departement: '69 - Rhône', region: 'Auvergne-Rhône-Alpes' },
  { slug: 'toulouse', nom: 'Toulouse', departement: '31 - Haute-Garonne', region: 'Occitanie' },
  { slug: 'nice', nom: 'Nice', departement: '06 - Alpes-Maritimes', region: 'Provence-Alpes-Côte d\'Azur' },
  { slug: 'nantes', nom: 'Nantes', departement: '44 - Loire-Atlantique', region: 'Pays de la Loire' },
  { slug: 'montpellier', nom: 'Montpellier', departement: '34 - Hérault', region: 'Occitanie' },
  { slug: 'strasbourg', nom: 'Strasbourg', departement: '67 - Bas-Rhin', region: 'Grand Est' },
  { slug: 'bordeaux', nom: 'Bordeaux', departement: '33 - Gironde', region: 'Nouvelle-Aquitaine' },
  { slug: 'lille', nom: 'Lille', departement: '59 - Nord', region: 'Hauts-de-France' },
  { slug: 'rennes', nom: 'Rennes', departement: '35 - Ille-et-Vilaine', region: 'Bretagne' },
  { slug: 'reims', nom: 'Reims', departement: '51 - Marne', region: 'Grand Est' },
  { slug: 'toulon', nom: 'Toulon', departement: '83 - Var', region: 'Provence-Alpes-Côte d\'Azur' },
  { slug: 'saint-etienne', nom: 'Saint-Étienne', departement: '42 - Loire', region: 'Auvergne-Rhône-Alpes' },
  { slug: 'le-havre', nom: 'Le Havre', departement: '76 - Seine-Maritime', region: 'Normandie' },
  { slug: 'dijon', nom: 'Dijon', departement: '21 - Côte-d\'Or', region: 'Bourgogne-Franche-Comté' },
  { slug: 'grenoble', nom: 'Grenoble', departement: '38 - Isère', region: 'Auvergne-Rhône-Alpes' },
  { slug: 'angers', nom: 'Angers', departement: '49 - Maine-et-Loire', region: 'Pays de la Loire' },
  { slug: 'villeurbanne', nom: 'Villeurbanne', departement: '69 - Rhône', region: 'Auvergne-Rhône-Alpes' },
  { slug: 'nimes', nom: 'Nîmes', departement: '30 - Gard', region: 'Occitanie' },
  { slug: 'clermont-ferrand', nom: 'Clermont-Ferrand', departement: '63 - Puy-de-Dôme', region: 'Auvergne-Rhône-Alpes' },
  { slug: 'aix-en-provence', nom: 'Aix-en-Provence', departement: '13 - Bouches-du-Rhône', region: 'Provence-Alpes-Côte d\'Azur' },
  { slug: 'le-mans', nom: 'Le Mans', departement: '72 - Sarthe', region: 'Pays de la Loire' },
  { slug: 'brest', nom: 'Brest', departement: '29 - Finistère', region: 'Bretagne' },
  { slug: 'tours', nom: 'Tours', departement: '37 - Indre-et-Loire', region: 'Centre-Val de Loire' },
  { slug: 'amiens', nom: 'Amiens', departement: '80 - Somme', region: 'Hauts-de-France' },
  { slug: 'limoges', nom: 'Limoges', departement: '87 - Haute-Vienne', region: 'Nouvelle-Aquitaine' },
  { slug: 'annecy', nom: 'Annecy', departement: '74 - Haute-Savoie', region: 'Auvergne-Rhône-Alpes' },
  { slug: 'boulogne-billancourt', nom: 'Boulogne-Billancourt', departement: '92 - Hauts-de-Seine', region: 'Île-de-France' },
  { slug: 'perpignan', nom: 'Perpignan', departement: '66 - Pyrénées-Orientales', region: 'Occitanie' },
  { slug: 'metz', nom: 'Metz', departement: '57 - Moselle', region: 'Grand Est' },
  { slug: 'besancon', nom: 'Besançon', departement: '25 - Doubs', region: 'Bourgogne-Franche-Comté' },
  { slug: 'orleans', nom: 'Orléans', departement: '45 - Loiret', region: 'Centre-Val de Loire' },
  { slug: 'saint-denis', nom: 'Saint-Denis', departement: '93 - Seine-Saint-Denis', region: 'Île-de-France' },
  { slug: 'rouen', nom: 'Rouen', departement: '76 - Seine-Maritime', region: 'Normandie' },
  { slug: 'argenteuil', nom: 'Argenteuil', departement: '95 - Val-d\'Oise', region: 'Île-de-France' },
  { slug: 'montreuil', nom: 'Montreuil', departement: '93 - Seine-Saint-Denis', region: 'Île-de-France' },
  { slug: 'mulhouse', nom: 'Mulhouse', departement: '68 - Haut-Rhin', region: 'Grand Est' },
  { slug: 'caen', nom: 'Caen', departement: '14 - Calvados', region: 'Normandie' },
  { slug: 'nancy', nom: 'Nancy', departement: '54 - Meurthe-et-Moselle', region: 'Grand Est' },
  { slug: 'tourcoing', nom: 'Tourcoing', departement: '59 - Nord', region: 'Hauts-de-France' },
  { slug: 'roubaix', nom: 'Roubaix', departement: '59 - Nord', region: 'Hauts-de-France' },
  { slug: 'nanterre', nom: 'Nanterre', departement: '92 - Hauts-de-Seine', region: 'Île-de-France' },
  { slug: 'vitry-sur-seine', nom: 'Vitry-sur-Seine', departement: '94 - Val-de-Marne', region: 'Île-de-France' },
  { slug: 'creteil', nom: 'Créteil', departement: '94 - Val-de-Marne', region: 'Île-de-France' },
  { slug: 'avignon', nom: 'Avignon', departement: '84 - Vaucluse', region: 'Provence-Alpes-Côte d\'Azur' },
  { slug: 'poitiers', nom: 'Poitiers', departement: '86 - Vienne', region: 'Nouvelle-Aquitaine' },
  { slug: 'aubervilliers', nom: 'Aubervilliers', departement: '93 - Seine-Saint-Denis', region: 'Île-de-France' },
  { slug: 'dunkerque', nom: 'Dunkerque', departement: '59 - Nord', region: 'Hauts-de-France' },
  { slug: 'versailles', nom: 'Versailles', departement: '78 - Yvelines', region: 'Île-de-France' },
  { slug: 'courbevoie', nom: 'Courbevoie', departement: '92 - Hauts-de-Seine', region: 'Île-de-France' },
  { slug: 'colombes', nom: 'Colombes', departement: '92 - Hauts-de-Seine', region: 'Île-de-France' },
  { slug: 'asnieres-sur-seine', nom: 'Asnières-sur-Seine', departement: '92 - Hauts-de-Seine', region: 'Île-de-France' },
  { slug: 'aulnay-sous-bois', nom: 'Aulnay-sous-Bois', departement: '93 - Seine-Saint-Denis', region: 'Île-de-France' },
  { slug: 'la-rochelle', nom: 'La Rochelle', departement: '17 - Charente-Maritime', region: 'Nouvelle-Aquitaine' },
  { slug: 'calais', nom: 'Calais', departement: '62 - Pas-de-Calais', region: 'Hauts-de-France' },
  { slug: 'cannes', nom: 'Cannes', departement: '06 - Alpes-Maritimes', region: 'Provence-Alpes-Côte d\'Azur' },
  { slug: 'antibes', nom: 'Antibes', departement: '06 - Alpes-Maritimes', region: 'Provence-Alpes-Côte d\'Azur' },
  { slug: 'beziers', nom: 'Béziers', departement: '34 - Hérault', region: 'Occitanie' },
  { slug: 'bourges', nom: 'Bourges', departement: '18 - Cher', region: 'Centre-Val de Loire' },
  { slug: 'saint-nazaire', nom: 'Saint-Nazaire', departement: '44 - Loire-Atlantique', region: 'Pays de la Loire' },
  { slug: 'valence', nom: 'Valence', departement: '26 - Drôme', region: 'Auvergne-Rhône-Alpes' },
]
